name: springboot-sns-example

services:
  redis:
    image: redis:7-alpine
    container_name: springboot-sns-example-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:17-alpine
    container_name: springboot-sns-example-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sns
      POSTGRES_USER: sns
      POSTGRES_PASSWORD: sns123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
